### ISSUE TITLE
0.14 Randomly triggers all buttons

### ISSUE THREAD

**Issue by NewsGuyTor** [thomasloven/hass-plejd#97]
Thanks for v0.14, really nice to be able to map things to a single button press to things! 

However, I'm having a huge issue. Suddenly and abruptly Plejd goes unavailable and all Plejd events/buttons are fired. Second time now.

This is a massive problem, as it triggers automations that lights up my whole apartment randomly. I've had to disable all Plejd automations for now until this is fixed, except a test one that doesn't make my bedroom bright.

Here's a clip:

https://github.com/user-attachments/assets/cc3b09a2-8684-4512-a8fa-490d045ff642

Before the start of the video there nothing happening in HA:
<img width="470" alt="Skjermbilde 2025-01-09 kl  04 31 43" src="https://github.com/user-attachments/assets/2eba1cd4-830c-4556-9eff-f96585da28d8" />

The HA logs only shows Plejd errors from after the avalanche, likely from trying to execute so much at the same time. I've changed it to info and the Plejd debug settings, so I'll have more to report the next time it happens.

**Comment by Lisnol** [comment]
Having the same problem. Also triggers when you restart home assistant (they become unavailable).

Another thing, when pressing button long, I get two events, as expected, but they both shows pressed. Not pressed and then released.

**Comment by edbgon** [comment]
I was wondering why my lights were still on today after I had shut them off. Seems like buttons are triggering after the device goes unavailable?

![image](https://github.com/user-attachments/assets/486cfd13-4a61-403d-8e70-ba7f82df9486)

**Comment by thomasloven** [comment]
This is unfortunately the behavior of `event` entities.
A bug, i.m.o.

https://github.com/home-assistant/core/issues/131932

**Comment by NewsGuyTor** [comment]
How will we work around this in the meantime? Home Assistant will likely take months fixing this.

We can't use buttons for most useful stuff if they "click themselves" randomly.

**Comment by Lisnol** [comment]
Try this:
entity_id:
  - event.scenesovrumtak_activated
id: gardin
trigger: state
not_from:
  - unknown
  - unavailable
not_to:
  - unknown
  - unavailable

**Comment by Lisnol** [comment]
Remove this lines
attribute: event_type
to: press

**Comment by thomasloven** [comment]
You probably can't have both `to` and `not_to`...

**Comment by Lisnol** [comment]
True. But I also have to remove attribute to make it work

**Comment by NewsGuyTor** [comment]
Thanks, that seems to work. Things aren't going crazy anymore when reloading Plejd. 

Here's an example of a working automation for people to copy and modify:

```
alias: NameOfAutomation
description: "Putyourdescriptionhere"
triggers:
  - trigger: state
    entity_id:
      - event.plejd_kontor_knapp
    not_from:
      - unknown
      - unavailable
    not_to:
      - unknown
      - unavailable
conditions: []
actions:
  - target:
      entity_id:
        - light.nanoleaf_lines
    action: light.toggle
    data: {}
mode: single
```
